### ISSUE TITLE
[TASK] PLONK Mixer circuit

### ISSUE THREAD

**Issue by filiplazovic** [webb-tools/arkworks-gadgets#121]
Mixer circuit should have inputs:
```rust
secret: F,
nullifier: F,
nullifier_hash: F,
path: Path<..>,
root: F,
arbitrary_data: F,
// In mixer case, these two are the same, so we should just pass one hasher
tree_hasher: H::Native,
leaf_hasher: H::Native
```
The `secret` is a random number that will be kept secret and will not be revealed. The nullifier is also generated randomly, but it is revealed during the verification to prevent double spending.

To prevent front-run attacks (https://ethresear.ch/t/anonymous-reputation-risking-and-burning/3926 <-- see comments), hash of the nullifier is introduced. `nullifier_hash` is also an (public) input to the circuit, and we will check if `nullifier_hash == hash(nullifier)`. After the proof is verified, `nullifier_hash` is stored inside chain storage.

`path` is the merkle path. It's a private input, which means all the nodes are hidden. We will use it to calculate root, and then check if it's equal to the passed `root` (`path.calculate_root() == root`) which is a public input. This `root` is a public input, and it will be fetched from on-chain storage, and passed into the circuit.

`Arbitrary data` - arbitrary constrains that will be included in the proof. // To be discussed

Out of these, private inputs are:
`secret`, `nullifier`, `path`
Public inputs are:
`nullifier_hash`, `root`, `arbitrary_data`

Higher-level description of how the Mixer circuit works:
```rust
// Making the leaf from secret and nullifier
let leaf = leaf_hasher_gadget.hash_two(secret, nullifier);
// Making the nullifier hash from nullifier
let calc_nullifier_hash = leaf_hasher_gadget.hash_two(nullifier, nullifier); // or leaf_hasher.hash(&[nullifier]) needs to be discussed

// Making sure that passed nullifier hash is the same as calculated one
composer.assert_equal(nullifier_hash, calc_nullifier_hash);

// Calculating the root using the provided path
let calc_root = path_gadget.calculate_root(leaf, &tree_hasher_gadget);

// Making sure that calculated root matches the passed one
composer.assert_equal(root, calc_root);

// Constraining arbitrary data
let _ = arbitrary_data * arbitrary_data; // to be discussed
```
NOTE: `tree_hasher` and `leaf_hasher` are the same in case of a mixer circuit, so we should pass one hasher

Checklist:
- [x] Implement PLONK version of mixer circuit
- [ ] Add tests for PLONK Mixer circuit

**Comment by drewstone** [comment]
1. We are hashing the nullifier in order to create a public input that once exposed and stored on chain prevents double-spending. Semantically we may have chose the wrong word here. In the article, it is referred to as the nullifier_secret and the hash of it is referred to as the nullifier. Here, we refer to the secret component as the nullifier and the exposed value as the nullifier hash. This shouldn't be an issue if we understand this conceptually.
2. The hash of a single or pair of elements doesn't matter. The key thing here is that we provide a hash of a secret value(s) that will always be required when making proofs. If a user tries to verify the proof twice in an application using this circuits verifier -- and we store these hashes on that application to prevent double spending -- then they will have to expose the same hash and we can reject such a transaction.

Note that these hashes are needed not from the circuits point of view but rather from the application that uses the circuits point of view. 

3.

**Comment by filiplazovic** [comment]
Copied from our conversation:

> The front running is because in the first proposed design they would supply a public external nullifier and also use that in the hash of a leaf afaik. So there would be a visible mark on the tx that could invalidate someone's leaf if I submit the same nullifier in my leaf first.

> Even if you front run with the nullifier you'd have to also know the preimage in order to verify against our circuit. This would require you to invert Poseidon.

**Comment by filiplazovic** [comment]
@drew We switched to using one arbitrary value as an input to the circuit. It can be a hash of all the neccessary inputs, like we do in vanchor

**Comment by GhostOfGauss** [comment]
I set the issue to close with the Plonk Mixer PR but since that did not include tests it should remain open.

**Comment by GhostOfGauss** [comment]
Which tests should we include? 

*   Obviously a test where all information is correctly input and we check that the proof verifies properly.
*   Failure cases:
    *   wrong secret
    *   wrong nullifier
    *   path with wrong root
    *   path with wrong leaf 
    *   used wrong nullifier hash
    *   prover/verifier disagree on arbitrary data 
    *   ? Any others ? 

There's also the question of when to go through the entire proof generation/verification sequence versus just using `check_circuit_is_satisfied`.  The latter is a lightweight check that grabs the values underlying each variable and checks that they satisfy each constraint.  It is significantly faster because it does not actually do all the hard work of generating and verifying the proof.

I think it makes sense to do a full proof generation/verification in the first case (correct circuit that should pass) and for the rest to confirm that the test will fail by testing that `check_circuit_is_satisfied` fails.

**Comment by filiplazovic** [comment]
Few more ideas:
- Since we didn't test our Merkle tree thoroughly, perhaps use a tree with smaller height, populate it fully, and test the membership of the last leaf.
- While verifying, change the values of every public input individually (nullifier_hash, root, and arbitrary data).

When it comes to `check_circuit_is_satisfied` I'm not sure in this case. #140 was related to smaller gadgets (PathGadget, PoseidonGadget, SetGadget, etc.) since they are intermediate piece of computation and not full circuit.
I would include both of them, since we do care about the whole prove/verify process in this case.

**Comment by GhostOfGauss** [comment]
Wanna hear something surprising? 

Turns out that `check_circuit_is_satisfied` takes significantly longer to run on a bad proof than the full proof generation / verification routine.  In [this example](https://github.com/webb-tools/arkworks-gadgets/blob/176c8fe52ac449ebdd6f25deb212d2ed4ee1732e/arkworks-plonk-circuits/src/mixer/mod.rs#L268-L312) it took 9 times as long (the other test is right below and runs in about 50 seconds).  

And thanks for the ideas above, I'll include those suggestions.

**Comment by filiplazovic** [comment]
Yea, that's surprising. Try getting to the bottom of it (ask on discord also). Also try to run tests in `--release` mode.
